# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello',
  syntax='proto3',
  serialized_pb=_b('\n\x0bhello.proto\x12\x05hello\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x08Response\x12\x0b\n\x03val\x18\x01 \x01(\t\"\x1c\n\x0c\x42\x61tchRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\"\x1c\n\rBatchResponse\x12\x0b\n\x03val\x18\x01 \x03(\t2h\n\x05Hello\x12\'\n\x04\x45\x63ho\x12\x0e.hello.Request\x1a\x0f.hello.Response\x12\x36\n\tBatchEcho\x12\x13.hello.BatchRequest\x1a\x14.hello.BatchResponseb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='hello.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello.Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='hello.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='hello.Response.val', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=70,
)


_BATCHREQUEST = _descriptor.Descriptor(
  name='BatchRequest',
  full_name='hello.BatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello.BatchRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=100,
)


_BATCHRESPONSE = _descriptor.Descriptor(
  name='BatchResponse',
  full_name='hello.BatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='hello.BatchResponse.val', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['BatchRequest'] = _BATCHREQUEST
DESCRIPTOR.message_types_by_name['BatchResponse'] = _BATCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.Response)
  ))
_sym_db.RegisterMessage(Response)

BatchRequest = _reflection.GeneratedProtocolMessageType('BatchRequest', (_message.Message,), dict(
  DESCRIPTOR = _BATCHREQUEST,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.BatchRequest)
  ))
_sym_db.RegisterMessage(BatchRequest)

BatchResponse = _reflection.GeneratedProtocolMessageType('BatchResponse', (_message.Message,), dict(
  DESCRIPTOR = _BATCHRESPONSE,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.BatchResponse)
  ))
_sym_db.RegisterMessage(BatchResponse)



_HELLO = _descriptor.ServiceDescriptor(
  name='Hello',
  full_name='hello.Hello',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=132,
  serialized_end=236,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='hello.Hello.Echo',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BatchEcho',
    full_name='hello.Hello.BatchEcho',
    index=1,
    containing_service=None,
    input_type=_BATCHREQUEST,
    output_type=_BATCHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLO)

DESCRIPTOR.services_by_name['Hello'] = _HELLO

# @@protoc_insertion_point(module_scope)
