# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class HelloStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/hello.Hello/Echo',
        request_serializer=hello__pb2.Request.SerializeToString,
        response_deserializer=hello__pb2.Response.FromString,
        )
    self.BatchEcho = channel.unary_unary(
        '/hello.Hello/BatchEcho',
        request_serializer=hello__pb2.BatchRequest.SerializeToString,
        response_deserializer=hello__pb2.BatchResponse.FromString,
        )


class HelloServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BatchEcho(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=hello__pb2.Request.FromString,
          response_serializer=hello__pb2.Response.SerializeToString,
      ),
      'BatchEcho': grpc.unary_unary_rpc_method_handler(
          servicer.BatchEcho,
          request_deserializer=hello__pb2.BatchRequest.FromString,
          response_serializer=hello__pb2.BatchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hello.Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
